# Generated by Django 4.0.5 on 2022-06-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=120)),
                ('Estado', models.BooleanField(default=True)),
                ('Rol', models.CharField(max_length=50)),
                ('Correo', models.CharField(max_length=100)),
                ('Contraseña', models.CharField(max_length=255)),
            ],
        ),
    ]
